---
namespace: blueprints
name: jenkins
version: 0.1.0
readme: README.md
authors:
  - Platform Engineering
description: "Reusable, org-agnostic Jenkins building blocks (no hidden dependencies)."
license:
  - MIT
tags:
  - tools
  - blueprints
  - jenkins
repository: https://github.com/iac-foundry/ansible-collection-jenkins
dependencies: {}
build_ignore:
  - .github
  - "*.tar.gz"
  - extensions
